{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import os\n",
    "from matplotlib import pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "%matplotlib inline"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Data Loading\n",
    "### focus on journals related to finance, economics, management, etc., specifically:\n",
    "<ol>\n",
    "  <li>from CABS file use all journals in spreadsheet “CABS 2021”</li>\n",
    "  <li>from JCR files use all journals in spreadsheets: BUSINESS, BUSINESS, FINANCE, ECONOMICS, MANAGEMENT\n",
    "</li>\n",
    "  <li>from “Wykaz…” files use the journals from the following:\n",
    "ekonomia i finanse\t\tnauki o zarządzaniu i jakości\n",
    "501\t\t506;\n",
    "Use only spreadsheet “czasopisma naukowe”\n",
    "</li>\n",
    "</ol>\n",
    "\n",
    "Note that if the journal appears at least in one of the source, it has to be taken into account\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of openpyxl.descriptors failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 361, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 319, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: can't apply this __setattr__ to MetaStrict object\n",
      "]\n",
      "[autoreload of openpyxl.styles.alignment failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'textRotation'\n",
      "]\n",
      "[autoreload of openpyxl.styles.borders failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'style'\n",
      "]\n",
      "[autoreload of openpyxl.styles.fills failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'patternType'\n",
      "]\n",
      "[autoreload of openpyxl.styles.fonts failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'sz'\n",
      "]\n",
      "[autoreload of openpyxl.styles.cell_style failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\styles\\cell_style.py\", line 27, in __get__\n",
      "    return instance[self.key]\n",
      "           ~~~~~~~~^^^^^^^^^^\n",
      "TypeError: 'NoneType' object is not subscriptable\n",
      "]\n",
      "[autoreload of openpyxl.styles.styleable failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\styles\\styleable.py\", line 31, in __get__\n",
      "    coll = getattr(instance.parent.parent, self.collection)\n",
      "                   ^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'parent'\n",
      "]\n",
      "[autoreload of openpyxl.cell.text failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 't'\n",
      "]\n",
      "[autoreload of openpyxl.styles.differential failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'dxf'\n",
      "]\n",
      "[autoreload of openpyxl.formatting.formatting failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'sqref'\n",
      "]\n",
      "[autoreload of openpyxl.packaging.relationship failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'Target'\n",
      "]\n",
      "[autoreload of openpyxl.worksheet.header_footer failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'center'\n",
      "]\n",
      "[autoreload of openpyxl.workbook.defined_name failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'attr_text'\n",
      "]\n",
      "[autoreload of openpyxl.worksheet.datavalidation failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'sqref'\n",
      "]\n",
      "[autoreload of openpyxl.worksheet.dimensions failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'outlineLevel'\n",
      "]\n",
      "[autoreload of openpyxl.worksheet.protection failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'sheet'\n",
      "]\n",
      "[autoreload of openpyxl.worksheet.filters failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'colId'\n",
      "]\n",
      "[autoreload of openpyxl.worksheet.table failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'attr_text'\n",
      "]\n",
      "[autoreload of openpyxl.comments.author failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'author'\n",
      "]\n",
      "[autoreload of openpyxl.chart.layout failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'w'\n",
      "]\n",
      "[autoreload of openpyxl.drawing.colors failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'scrgbClr'\n",
      "]\n",
      "[autoreload of openpyxl.drawing.fill failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'prst'\n",
      "]\n",
      "[autoreload of openpyxl.drawing.line failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'd'\n",
      "]\n",
      "[autoreload of openpyxl.drawing.geometry failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'cx'\n",
      "]\n",
      "[autoreload of openpyxl.chart.shapes failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'xfrm'\n",
      "]\n",
      "[autoreload of openpyxl.drawing.text failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'rPr'\n",
      "]\n",
      "[autoreload of openpyxl.chart.data_source failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'f'\n",
      "]\n",
      "[autoreload of openpyxl.chart.text failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'bodyPr'\n",
      "]\n",
      "[autoreload of openpyxl.chart.error_bar failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'errDir'\n",
      "]\n",
      "[autoreload of openpyxl.chart.marker failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'spPr'\n",
      "]\n",
      "[autoreload of openpyxl.chart._3d failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'rotX'\n",
      "]\n",
      "[autoreload of openpyxl.chart.legend failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'legendPos'\n",
      "]\n",
      "[autoreload of openpyxl.chart.label failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'spPr'\n",
      "]\n",
      "[autoreload of openpyxl.chart.trendline failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'spPr'\n",
      "]\n",
      "[autoreload of openpyxl.chart.series failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'v'\n",
      "]\n",
      "[autoreload of openpyxl.chart.title failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'tx'\n",
      "]\n",
      "[autoreload of openpyxl.chart._chart failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'ser'\n",
      "]\n",
      "[autoreload of openpyxl.chart.axis failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'spPr'\n",
      "]\n",
      "[autoreload of openpyxl.chart.area_chart failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'dLbls'\n",
      "]\n",
      "[autoreload of openpyxl.chart.bar_chart failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'barDir'\n",
      "]\n",
      "[autoreload of openpyxl.chart.bubble_chart failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'dLbls'\n",
      "]\n",
      "[autoreload of openpyxl.chart.line_chart failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'dLbls'\n",
      "]\n",
      "[autoreload of openpyxl.chart.pie_chart failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'dLbls'\n",
      "]\n",
      "[autoreload of openpyxl.chart.radar_chart failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'radarStyle'\n",
      "]\n",
      "[autoreload of openpyxl.chart.scatter_chart failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'dLbls'\n",
      "]\n",
      "[autoreload of openpyxl.chart.stock_chart failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'dLbls'\n",
      "]\n",
      "[autoreload of openpyxl.chart.surface_chart failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'spPr'\n",
      "]\n",
      "[autoreload of openpyxl.drawing.connector failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'nvSpPr'\n",
      "]\n",
      "[autoreload of openpyxl.drawing.picture failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'spPr'\n",
      "]\n",
      "[autoreload of openpyxl.drawing.graphic failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'nvGrpSpPr'\n",
      "]\n",
      "[autoreload of openpyxl.drawing.spreadsheet_drawing failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'sp'\n",
      "]\n",
      "[autoreload of openpyxl.workbook.protection failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'workbookPassword'\n",
      "]\n",
      "[autoreload of openpyxl.packaging.workbook failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'workbookPr'\n",
      "]\n",
      "[autoreload of openpyxl.chartsheet.relation failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'lho'\n",
      "]\n",
      "[autoreload of openpyxl.chartsheet.chartsheet failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'headerFooter'\n",
      "]\n",
      "[autoreload of openpyxl.packaging.core failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'lastModifiedBy'\n",
      "]\n",
      "[autoreload of openpyxl.workbook.workbook failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 345, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 305, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: create_named_range() requires a code object with 3 free vars, not 1962800054272\n",
      "]\n",
      "[autoreload of openpyxl.chart.plotarea failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'spPr'\n",
      "]\n",
      "[autoreload of openpyxl.chart.pivot failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'spPr'\n",
      "]\n",
      "[autoreload of openpyxl.chart.print_settings failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'l'\n",
      "]\n",
      "[autoreload of openpyxl.chart.chartspace failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Alon\\AppData\\Roaming\\Python\\Python311\\site-packages\\IPython\\extensions\\autoreload.py\", line 326, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\openpyxl\\descriptors\\base.py\", line 230, in __get__\n",
      "    return getattr(instance, self.alias)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'spPr'\n",
      "]\n"
     ]
    }
   ],
   "source": [
    "# Specify the directory containing your Excel files\n",
    "directory_path = 'source files'\n",
    "\n",
    "# Get a list of all Excel files in the directory\n",
    "excel_files = [file for file in os.listdir(directory_path) if file.endswith('.xlsx')]\n",
    "\n",
    "# Create an empty dictionary to store the loaded data frames\n",
    "data_frames = {}\n",
    "\n",
    "# Load from CABS file\n",
    "cabs_file = [file for file in excel_files if \"CABS\" in file][0]\n",
    "cabs_sheet = \"CABS 2021\"\n",
    "cabs_file_path = os.path.join(directory_path, cabs_file)\n",
    "try:\n",
    "    cabs_df = pd.read_excel(cabs_file_path, sheet_name=cabs_sheet)\n",
    "    data_frames[cabs_file] = cabs_df\n",
    "except Exception as e:\n",
    "    print(f\"Error loading {cabs_file}: {e}\")\n",
    "\n",
    "# Load from JCR files\n",
    "jcr_files = [file for file in excel_files if \"JCR\" in file]\n",
    "jcr_sheets = [\"BUSINESS\", \"BUSINESS, FINANCE\", \"ECONOMICS\", \"MANAGEMENT\"]\n",
    "for jcr_file in jcr_files:\n",
    "    jcr_file_path = os.path.join(directory_path, jcr_file)\n",
    "    try:\n",
    "        jcr_df = pd.read_excel(jcr_file_path, sheet_name=jcr_sheets)\n",
    "        data_frames[jcr_file] = jcr_df\n",
    "    except Exception as e:\n",
    "        print(f\"Error loading {jcr_file}: {e}\")\n",
    "\n",
    "# Load from files containing the word “Wykaz”\n",
    "wykaz_files = [file for file in excel_files if \"Wykaz\" in file]\n",
    "for wykaz_file in wykaz_files:\n",
    "    wykaz_file_path = os.path.join(directory_path, wykaz_file)\n",
    "    try:\n",
    "        wykaz_df = None\n",
    "        with pd.ExcelFile(wykaz_file_path) as xls:\n",
    "            for sheet_name in xls.sheet_names:\n",
    "                if \"czasopisma\" in sheet_name.lower():\n",
    "                    wykaz_df = pd.read_excel(wykaz_file_path, sheet_name=sheet_name, engine='openpyxl')\n",
    "                    data_frames[wykaz_file] = wykaz_df\n",
    "                    break\n",
    "        if wykaz_df is None:\n",
    "            print(f\"No sheet containing 'czasopisma' found in {wykaz_file}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error loading {wykaz_file}: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "dict_keys(['CABS Journal Ranking 2021.xlsx', 'JCR_2021_ALL.xlsx', 'JCR_2022_ALL.xlsx', '20211201_Wykaz_dyscyplin_przypisanych_do_czasopism_naukowych_i_materiałów_konferencyjnych - Dec 2021 1.xlsx', '20240105_Wykaz_czasopism_naukowych_2024_styczeń.xlsx', 'Wykaz_dyscyplin_do_czasopism_i_materiałów_konferencyjnych Feb 2021.xlsx'])"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data_frames.keys()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
